version: '3.8'

services:
  nextjs-app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - nextjs-app-node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    stdin_open: true
    tty: true

volumes:
  nextjs-app-node_modules: